version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: happychoices
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_stuff/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db_stuff/zdata.sql:/docker-entrypoint-initdb.d/zdata.sql

  app:
    build: .
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: happychoices
    stdin_open: true # Keep the container open to receive input
    tty: true        # Allocate a pseudo-TTY

volumes:
  mysql_data:
